Improved type error reporting (#38)
propagate the reason why expression type cannot be determined to the compiler error message.

Old error message:
```
error: ./test/datalog_tests/function.fail.dl:6:5-7:1: Expression parameterized(string, int) has unknown type in CtxTop
```

New error message
```
error: ./test/datalog_tests/function.fail.dl:6:5-8:1: Conflicting types string and int for type variable 'A in call to function parameterized (x: 'A, y: 'A): 'A
```