Bump required rustc version to 1.36+.
The latest DD fails to compile with earlier rust's:

```
   Compiling differential-dataflow v0.10.0 (https://github.com/ryzhyk/differential-dataflow?branch=0.10.2#2caae73d)
error[E0506]: cannot assign to `**count` because it is borrowed
   --> /root/.cargo/git/checkouts/differential-dataflow-b5c2296e75e08b32/2caae73/src/operators/threshold.rs:173:37
    |
169 |                                 if let Some(count) = &mut count {
    |                                                           ----- borrow of `**count` occurs here
...
173 |                                     count = Some(diff.clone());
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `**count` occurs here
```