GCC-like error message format that Emacs can parse.
Until now, ddlog error messages have had the format
    ddlog: error: FILE:LINE1:COL1-LINE2:COL2: ...
Emacs doesn't parse this.  This commit changes the format to
    error: FILE:LINE1.COL1-LINE2.COL2: ...
which is similar to GCC and which Emacs understands.