Do not quit CLI on errors
When using the CLI that is provided with each generated ddlog program,
some errors are effectively ignored (in the sense that they don't
terminate the program; arguably sensible behavior), while others cause
program exit. E.g.,
  > >> list;
  > Invalid input: list;,
  > >> hello;
  > Invalid input: hello;,
  (we can just continue)

But:
  > >> dump Left;
  > Error: Unknown output relation Left
  $
  (we exit on this path)

The latter behavior can be very frustrating, as it can mean that an
interactive session into which data was fed manually can accidentally be
terminated just by virtue of misspelling a relation, for example.
This change fixes the problem. It piggy backs on the logic to detect
whether a TTY is present and treats errors as benign, if it is present.

Bonus: Rename run_interactive to run, which seems to be a bit of a
       misleading name as it is also used in the non-interactive case.