Compile.hs: compatibility with latest rustc
Compilation failed with rustc 1.37 with the following error:

```
trait objects without an explicit `dyn` are deprecated
```