Add Unit() to standard library and document its use.
This add Unit to a new library file unit.dl.  I did try to add it to
ddlog_std.dl, instead, so that it would always be available.  This
works fine with the compiler, but whenever DDlog code actually tries
to use Unit in that case, the generated Rust fails to build with:

2547 error[E0308]: mismatched types
    --> types/ddlog_std/ddlog_std.rs:2548:122
     |
2548 | ...                   __f},
     |                       ^^^ expected enum `std::option::Option`, found enum `Option`
     |
     = note: expected fn pointer `fn(differential_datalog::ddval::DDValue) -> std::option::Option<(differential_datalog::ddval::DDValue, differential_datalog::ddval::DDValue)>`
                   found fn item `fn(differential_datalog::ddval::DDValue) -> Option<(differential_datalog::ddval::DDValue, differential_datalog::ddval::DDValue)> {__Arng_ddlog_std_Unit_0::{{closure}}#0::__f}`
error[E0308]: mismatched types
    --> types/ddlog_std/ddlog_std.rs:2543:126
     |
2540 |   ...                   afun: {fn __f(__v: DDValue) -> Option<(DDValue,DDValue)>
     |                                                        ------------------------- expected `Option<(differential_datalog::ddval::DDValue, differential_datalog::ddval::DDValue)>` because of return type
...
2543 | / ...                       match <Unit>::from_ddvalue(__v) {
2544 | | ...                           _ => Some((()).into_ddvalue()),
2545 | | ...                           _ => None
2546 | | ...                       }.map(|x|(x,__cloned))
     | |________________________________________________^ expected enum `Option`, found enum `std::option::Option`
     |
     = note: expected enum `Option<(differential_datalog::ddval::DDValue, differential_datalog::ddval::DDValue)>`
                found enum `std::option::Option<(differential_datalog::ddval::DDValue, differential_datalog::ddval::DDValue)>`