Fix cargo vendor usage to work with workspaces
Using `Cargo.full.toml` instead of `Cargo.toml` upset `cargo vendor`:

```

$ cargo vendor -s Cargo.full.toml > config.tmp
error: package `differential-datalog/rust/template/cmd_parser/Cargo.toml` is a member of the wrong workspace
expected: differential-datalog/rust/template/Cargo.full.toml
actual:   differential-datalog/rust/template/Cargo.toml
```